on:
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: windows-latest

    steps:
    - name: Install Nuitka
      run: pip install nuitka
    - name: nuitka
      run: python -m nuitka --standalone --output-filename="F HamLog 1" --windows-icon-from-ico=file\F_HamLog.ico --main=main.py --msvc=latest --windows-console-mode=attach --enable-plugin=pyside6 --windows-uac-admin
